---
- name: Install private key
  copy:
    dest: "{{ key_path }}"
    mode: 0660
    content: |
      {{ key }}
  notify: Reload Nginx

- name: Install certificate
  copy:
    dest: "{{ cert_path }}"
    mode: 0660
    content: |
      {{ cert }}
      {% if chain is string %}
      {{ chain }}
      {% else %}
      {% for intermediate in chain %}
      {{ intermediate }}
      {% endfor %}
      {% endif %}
  notify: Reload Nginx
