---
- name: Install Nginx package
  package:
    name: nginx
    state: installed

- name: Configure Nginx server
  template:
    src: nginx.conf.j2
    dest: "{{ ngx_config_path }}"
    validate: "nginx -tc %s"
  notify: Reload Nginx
