---
- name: Create a temporary directory
  tempfile:
    state: directory
  register: ngx_tmp_dir
  check_mode: false
  changed_when: false

- name: Bulk configure sites
  template:
    src: site.conf.j2
    dest: |-
      {%  if site.server.server_name is string %}
      {%    set first_name = site.server.server_name %}
      {%  else %}
      {%    set first_name = site.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set base_name = (first_name | replace('.', '', 1)) %}
      {%  else %}
      {%    set base_name = first_name %}
      {%  endif %}
      {{  ngx_tmp_dir.path }}/{{ site.name | default(base_name) }}.conf
  loop: "{{ sites }}"
  loop_control:
    loop_var: site
    label: |-
      {%  if site.server.server_name is string %}
      {%    set first_name = site.server.server_name %}
      {%  else %}
      {%    set first_name = site.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set base_name = (first_name | replace('.', '', 1)) %}
      {%  else %}
      {%    set base_name = first_name %}
      {%  endif %}
      {{  site.name | default(base_name) }}
  check_mode: false
  changed_when: false

- name: Assemble site configuration
  assemble:
    src: "{{ ngx_tmp_dir.path }}"
    dest: "{{ ngx_config_dir }}/{{ ngx_site_config }}"
    delimiter: "\n"
  notify: Reload Nginx

- name: Delete the temporary directory
  file:
    path: "{{ ngx_tmp_dir.path }}"
    state: absent
  check_mode: false
  changed_when: false
