---
- name: Configure site
  template:
    src: site.conf.j2
    dest: |-
      {%  if site.server.server_name is string %}
      {%    set first_name = site.server.server_name %}
      {%  else %}
      {%    set first_name = site.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set clean_name = first_name | replace('.', '', 1) %}
      {%  else %}
      {%    set clean_name = first_name %}
      {%  endif %}
      {%  if (site.server.listen | default(80)) != 80 %}
      {%    set suffix = '-' ~ site.server.listen %}
      {%  else %}
      {%    set suffix = '' %}
      {%  endif %}
      {{  ngx_config_dir }}/{{ clean_name }}{{ suffix }}.conf
