---
- name: Configure site
  template:
    src: site.conf.j2
    dest: |-
      {#  Detect the preferred server name #}
      {%  if site.server.server_name is not defined %}
      {%    set server_name = '' %}
      {%  elif site.server.server_name is string %}
      {%    set server_name = site.server.server_name %}
      {%  else %}
      {%    set server_name = site.server.server_name[0] %}
      {%  endif %}
      {#  Remove the leading dot from server name #}
      {%  if server_name[0] == '.' %}
      {%    set server = (server_name | replace('.', '', 1)) %}
      {%  endif %}
      {#  Detect the preferred listen port #}
      {%  if site.server.listen is not defined %}
      {%    set port = 80 %}
      {%  elif site.server.listen is number %}
      {%    set port = site.server.listen %}
      {%  elif site.server.listen is string %}
      {%    set port = site.server.listen.split(' ')[0] %}
      {%  else %}
      {%    set port = (site.server.listen[0] | string).split(' ')[0] %}
      {%  endif %}
      {#  Combine port and server name to uniquely identify the virtual host #}
      {{  ngx_config_dir }}/{{  port }}_{{ server_name }}.conf
  notify: Reload Nginx
