---
- name: Configure site
  template:
    src: site.conf.j2
    dest: |-
      {%  if site.settings.server.server_name is string %}
      {%    set first_name = site.settings.server.server_name %}
      {%  else %}
      {%    set first_name = site.settings.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set clean_name = first_name | replace('.', '', 1) %}
      {%  else %}
      {%    set clean_name = first_name %}
      {%  endif %}
      {{  ngx_config_dir }}/{{ clean_name }}.conf
