---
- name: Configure site
  template:
    src: site.conf.j2
    dest: |-
      {%  if site.server.server_name is string %}
      {%    set first_name = site.server.server_name %}
      {%  else %}
      {%    set first_name = site.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set clean_name = first_name | replace('.', '', 1) %}
      {%  else %}
      {%    set clean_name = first_name %}
      {%  endif %}
      {%  set default_port = site.server.ssl | default(false) | ternary(443, 80) %}
      {%  set listen_port = site.server.listen | default(80) %}
      {%  if listen_port != default_port %}
      {%    set suffix = '-' ~ listen_port %}
      {%  else %}
      {%    set suffix = '' %}
      {%  endif %}
      {{  ngx_config_dir }}/{{ ngx_site_base_name | default(clean_name ~ suffix  ~ '.conf') }}
