---
- name: Configure site
  template:
    src: site.conf.j2
    dest: |-
      {%  if site.server.server_name is string %}
      {%    set first_name = site.server.server_name %}
      {%  else %}
      {%    set first_name = site.server.server_name[0] %}
      {%  endif %}
      {%- if first_name[0] == '.' %}
      {%    set base_name = (first_name | replace('.', '', 1)) ~ '.conf' %}
      {%  else %}
      {%    set base_name = first_name ~ '.conf' %}
      {%  endif %}
      {{  ngx_config_dir }}/{{ ngx_site_base_name | default(base_name) }}
